spring:
   application:
      name: mysite07
   profiles:
      active: development

---
# common configuration
mysite:
   static:
      pathBase: /assets

spring:
   mvc:
      static-path-pattern: ${mysite.static.pathBase}/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         static-locations: classpath:${mysite.static.pathBase}, file:${mysite.upload.location}
   thymeleaf:
      prefix: classpath:templates/
      check-template-location: true
      mode: HTML
      suffix: .html
      cache: false
   servlet:
      multipart:
         enabled: true
         max-file-size: 20MB
         max-request-size: 100MB
mybatis:
   config-location: classpath:mybatis/configuration.xml

         
---
# development configuration
mysite:
   upload:
      location: /mysite-uploads

spring:
   config:
      activate:
         on-profile: development
   devtools:
      livereload:
         enabled: true
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.175:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb123
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO         


---
# production profile configuration
mysite:
   upload:
      location: /mysite-uploads

spring:
   config:
      activate:
         on-profile: production
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.175:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb123
server:
   port: 8082
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      com:
         poscodx:
            mysite:
               exception: ERROR