spring:
   application:
      name: service-registry-server
   profiles:
      active: development
      

---
# configuration: common

   
---
# configuration: development
spring:
   config:
      activate:
         on-profile: development
         
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO
      
---
# configuration: production
spring:
   config:
      activate:
         on-profile: production

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
                     