# spring configuration
spring:
   application:
      name: service-emaillist
   profiles:
      active: development

            
---
# configuration: common
spring:
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         static-locations: classpath:/assets/
         
mybatis:
   config-location: classpath:mybatis/configuration.xml



---
# configuration: development
spring:
   config:
      activate:
         on-profile: development

   devtools:
      livereload:
         enabled: true
                     
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO

           
                            
---
# configuration: production
spring:
   config:
      activate:
         on-profile: production

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://115.71.238.205:3306/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      com:
         poscodx:
            msa:
               service:
                  emaillist:
                     exception: ERROR
                              